/**
 * Validation utilities for comparing client-generated serialization
 * against canonical Minima node output.
 * 
 * Use the debug/export endpoint to get canonical bytes, then compare
 * with client-generated bytes to catch format divergence early.
 */

export interface ByteComparisonResult {
  match: boolean;
  clientLength: number;
  canonicalLength: number;
  firstDifferenceOffset: number | null;
  clientBytesAtDiff: string;
  canonicalBytesAtDiff: string;
  summary: string;
}

/**
 * Compare two hex strings byte-by-byte and report differences.
 * 
 * @param clientHex - Hex string generated by client serialization
 * @param canonicalHex - Hex string from Minima node (debug/export endpoint)
 * @returns Detailed comparison result
 */
export function compareSerializedBytes(
  clientHex: string,
  canonicalHex: string
): ByteComparisonResult {
  const cleanClient = clientHex.replace(/^0x/i, '').toLowerCase();
  const cleanCanonical = canonicalHex.replace(/^0x/i, '').toLowerCase();
  
  const clientLength = cleanClient.length / 2;
  const canonicalLength = cleanCanonical.length / 2;
  
  let firstDifferenceOffset: number | null = null;
  
  const minLen = Math.min(cleanClient.length, cleanCanonical.length);
  for (let i = 0; i < minLen; i += 2) {
    if (cleanClient.slice(i, i + 2) !== cleanCanonical.slice(i, i + 2)) {
      firstDifferenceOffset = i / 2;
      break;
    }
  }
  
  if (firstDifferenceOffset === null && cleanClient.length !== cleanCanonical.length) {
    firstDifferenceOffset = minLen / 2;
  }
  
  const match = firstDifferenceOffset === null;
  
  let clientBytesAtDiff = '';
  let canonicalBytesAtDiff = '';
  
  if (firstDifferenceOffset !== null) {
    const startByte = Math.max(0, firstDifferenceOffset - 4);
    const endByte = Math.min(Math.max(clientLength, canonicalLength), firstDifferenceOffset + 16);
    
    const startHex = startByte * 2;
    const endClientHex = Math.min(cleanClient.length, endByte * 2);
    const endCanonicalHex = Math.min(cleanCanonical.length, endByte * 2);
    
    clientBytesAtDiff = cleanClient.slice(startHex, endClientHex);
    canonicalBytesAtDiff = cleanCanonical.slice(startHex, endCanonicalHex);
  }
  
  let summary: string;
  if (match) {
    summary = `Exact match: ${clientLength} bytes`;
  } else if (clientLength > canonicalLength) {
    summary = `Client has ${clientLength - canonicalLength} extra bytes. First diff at offset ${firstDifferenceOffset}`;
  } else if (clientLength < canonicalLength) {
    summary = `Client missing ${canonicalLength - clientLength} bytes. First diff at offset ${firstDifferenceOffset}`;
  } else {
    summary = `Same length (${clientLength}) but content differs at offset ${firstDifferenceOffset}`;
  }
  
  return {
    match,
    clientLength,
    canonicalLength,
    firstDifferenceOffset,
    clientBytesAtDiff,
    canonicalBytesAtDiff,
    summary
  };
}

/**
 * Decode a TxnRow hex to understand its structure.
 * Useful for debugging serialization issues.
 */
export function decodeTxnRowStructure(hex: string): {
  id: { length: number; value: string; hex: string };
  transactionStart: number;
  totalLength: number;
} {
  const clean = hex.replace(/^0x/i, '');
  const bytes = new Uint8Array(clean.length / 2);
  for (let i = 0; i < clean.length; i += 2) {
    bytes[i / 2] = parseInt(clean.slice(i, i + 2), 16);
  }
  
  const idLength = (bytes[0] << 24) | (bytes[1] << 16) | (bytes[2] << 8) | bytes[3];
  const idBytes = bytes.slice(4, 4 + idLength);
  const idValue = new TextDecoder().decode(idBytes);
  const idHex = clean.slice(8, 8 + idLength * 2);
  
  return {
    id: { length: idLength, value: idValue, hex: idHex },
    transactionStart: 4 + idLength,
    totalLength: bytes.length
  };
}

/**
 * Log a detailed byte comparison for debugging.
 */
export function logByteComparison(
  clientHex: string,
  canonicalHex: string,
  label: string = 'Serialization Comparison'
): void {
  const result = compareSerializedBytes(clientHex, canonicalHex);
  
  console.group(`[ByteCompare] ${label}`);
  console.log('Match:', result.match ? '✅ YES' : '❌ NO');
  console.log('Client length:', result.clientLength, 'bytes');
  console.log('Canonical length:', result.canonicalLength, 'bytes');
  
  if (!result.match) {
    console.log('First difference at byte:', result.firstDifferenceOffset);
    console.log('Client bytes around diff:', result.clientBytesAtDiff);
    console.log('Canonical bytes around diff:', result.canonicalBytesAtDiff);
  }
  
  console.log('Summary:', result.summary);
  console.groupEnd();
}
