/**
 * RFC-009 Phase 2 — Minima Java → SDK TreeKey signature parity.
 *
 * `fixtures/minima-treekey-vector.json` is generated by the authoritative
 * Minima Java (`TreeKey(seed,4,2).sign(digest)`, serialized via
 * `Signature.writeDataStream()`). The SDK must deserialize it, verify it against
 * the Java root, re-serialize it identically, and accept it in the KISSVM
 * validator.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { hexToBytes, bytesToHex, deserializeTreeSignature, serializeTreeSignature, verifyTreeSignature } from '@totemsdk/core';
import { simulateSpend } from '@totemsdk/kissvm/simulate';
import { buildWitness } from '@totemsdk/kissvm/witness';
import type { CoinData, TxContext } from '@totemsdk/kissvm/types';

interface Vector {
  rootPublicKey: string;
  digest: string;
  signature: string;
}

const vector = JSON.parse(
  readFileSync(join(__dirname, 'fixtures', 'minima-treekey-vector.json'), 'utf8'),
) as Vector;

const COIN: CoinData = {
  amount: 100,
  tokenId: '0x00',
  coinId: '0x' + '11'.repeat(32),
  address: '0x' + '22'.repeat(32),
  coinCreatedBlock: 0,
};

jest.setTimeout(120_000);

describe('Minima Java -> SDK TreeKey signature parity (RFC-009 Phase 2)', () => {
  it('deserializes a Java Signature and verifies it against the Java root', () => {
    const sig = deserializeTreeSignature(hexToBytes(vector.signature));
    expect(verifyTreeSignature(hexToBytes(vector.rootPublicKey), hexToBytes(vector.digest), sig)).toBe(true);
  });

  it('re-serializes the Java signature identically (writeDataStream parity)', () => {
    const sig = deserializeTreeSignature(hexToBytes(vector.signature));
    const roundTrip = bytesToHex(serializeTreeSignature(sig)).toLowerCase();
    expect(roundTrip).toBe(vector.signature.slice(2).toLowerCase());
  });

  it('the KISSVM validator accepts the Java signature (SIGNEDBY against the Java root)', async () => {
    const sig = deserializeTreeSignature(hexToBytes(vector.signature));
    const ctx: TxContext = {
      block: 10,
      inputIndex: 0,
      inputs: [COIN],
      outputs: [],
      state: {},
      prevState: {},
      txDigest: hexToBytes(vector.digest),
    };
    const res = await simulateSpend(
      `RETURN SIGNEDBY(${vector.rootPublicKey})`,
      COIN,
      ctx,
      buildWitness([sig]),
    );
    expect(res.passed).toBe(true);
  });

  it('rejects the Java signature over a different digest', async () => {
    const sig = deserializeTreeSignature(hexToBytes(vector.signature));
    const ctx: TxContext = {
      block: 10,
      inputIndex: 0,
      inputs: [COIN],
      outputs: [],
      state: {},
      prevState: {},
      txDigest: new Uint8Array(32).fill(1),
    };
    const res = await simulateSpend(
      `RETURN SIGNEDBY(${vector.rootPublicKey})`,
      COIN,
      ctx,
      buildWitness([sig]),
    );
    expect(res.passed).toBe(false);
  });
});
