import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  conceptsSidebar: [
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/agent-policy-overview',
        'concepts/wots-key-management',
        'concepts/omnia-channels',
        'concepts/omnia-vtxo',
        'concepts/relay-modes',
        'concepts/totem-connect',
      ],
    },
  ],

  guidesSidebar: [
    {
      type: 'category',
      label: 'Setup & Configuration',
      collapsed: false,
      items: [
        'guides/typescript-configuration',
      ],
    },
    {
      type: 'category',
      label: 'Example Apps',
      collapsed: false,
      items: [
        'guides/tessa-pay',
        'guides/totem-personal-node',
        'guides/kissvm-studio',
        'guides/statechain-pass',
        'guides/omnia-pocket',
        'guides/channel-factory-wallet',
        'guides/omnia-router-node',
        'guides/totem-community-node',
        'guides/machinepay-edge',
      ],
    },
  ],

  apiSidebar: [
    {
      type: 'doc',
      id: 'api/index',
      label: 'Package Index',
    },
    {
      type: 'category',
      label: 'Core & Connect',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'api/totemsdk-core' },
        { type: 'autogenerated', dirName: 'api/totemsdk-connect' },
        { type: 'autogenerated', dirName: 'api/totemsdk-root-identity' },
        { type: 'autogenerated', dirName: 'api/totemsdk-server' },
        { type: 'autogenerated', dirName: 'api/totemsdk-wallet-adapter' },
      ],
    },
    {
      type: 'category',
      label: 'AI & Policy',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'api/totemsdk-agent-policy' },
        { type: 'autogenerated', dirName: 'api/totemsdk-manifest' },
      ],
    },
    {
      type: 'category',
      label: 'Omnia Channels',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'api/totemsdk-omnia' },
        { type: 'autogenerated', dirName: 'api/totemsdk-omnia-factory' },
        { type: 'autogenerated', dirName: 'api/totemsdk-omnia-router' },
        { type: 'autogenerated', dirName: 'api/totemsdk-omnia-splice' },
        { type: 'autogenerated', dirName: 'api/totemsdk-omnia-vtxo' },
      ],
    },
    {
      type: 'category',
      label: 'Edge Computing',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'api/totemsdk-edge' },
        { type: 'autogenerated', dirName: 'api/totemsdk-edge-adapters' },
        { type: 'autogenerated', dirName: 'api/totemsdk-edge-mqtt' },
        { type: 'autogenerated', dirName: 'api/totemsdk-pubsub-transport' },
        { type: 'autogenerated', dirName: 'api/totemsdk-stream-transport' },
      ],
    },
    {
      type: 'category',
      label: 'Identity & Proofs',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'api/totemsdk-identity' },
        { type: 'autogenerated', dirName: 'api/totemsdk-proof' },
        { type: 'autogenerated', dirName: 'api/totemsdk-proof-integritas' },
        { type: 'autogenerated', dirName: 'api/totemsdk-proofgraph' },
        { type: 'autogenerated', dirName: 'api/totemsdk-provider-bond' },
        { type: 'autogenerated', dirName: 'api/totemsdk-liquidity-bond' },
      ],
    },
    {
      type: 'category',
      label: 'Lookup & Routing',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'api/totemsdk-lookup-client' },
        { type: 'autogenerated', dirName: 'api/totemsdk-lookup-node' },
        { type: 'autogenerated', dirName: 'api/totemsdk-lookup-protocol' },
      ],
    },
    {
      type: 'category',
      label: 'Transactions & Cryptography',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'api/totemsdk-txpow' },
        { type: 'autogenerated', dirName: 'api/totemsdk-wots-lease' },
        { type: 'autogenerated', dirName: 'api/totemsdk-tx-builder' },
        { type: 'autogenerated', dirName: 'api/totemsdk-kissvm' },
        { type: 'autogenerated', dirName: 'api/totemsdk-statechain' },
        { type: 'autogenerated', dirName: 'api/totemsdk-se-server' },
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'api/totemsdk-chain-provider' },
        { type: 'autogenerated', dirName: 'api/totemsdk-realtime' },
        { type: 'autogenerated', dirName: 'api/totemsdk-pear' },
        { type: 'autogenerated', dirName: 'api/totemsdk-pureminima-rpc' },
      ],
    },
    {
      type: 'category',
      label: 'Browser & Platform',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'api/totem-observability' },
        { type: 'autogenerated', dirName: 'api/totem-extension-keyring' },
      ],
    },
  ],
};

export default sidebars;
