import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// ─── Manifest-driven API sidebar (RFC website-reorg §2.3) ───────────────────
// The package categories derive from `static/package-catalog.json`, which
// `scripts/generate.mjs` produces from SDK_MANIFEST.json's seven domains.
// Never hand-edit category members here — regenerate instead. The Package Index
// and the (only) hand-authored extension surfaces stay explicit below.
import catalog from './static/package-catalog.json';

interface CatalogDomain {
  id: string;
  label: string;
  packages: { slug: string }[];
}
interface Catalog {
  domains: CatalogDomain[];
  extensions: { slug: string; name: string }[];
}
const _catalog = catalog as Catalog;

if (!Array.isArray(_catalog?.domains)) {
  throw new Error(
    'sidebars.ts: static/package-catalog.json is missing or malformed. Run `npm run generate` (which reads SDK_MANIFEST.json) before starting the docs site.'
  );
}

const apiSidebar = [
  { type: 'doc' as const, id: 'api/index', label: 'Package Index' },
  ..._catalog.domains.map(domain => ({
    type: 'category' as const,
    label: domain.label,
    collapsed: true,
    items: domain.packages.map(pkg => ({ type: 'autogenerated' as const, dirName: `api/${pkg.slug}` })),
  })),
  {
    type: 'category' as const,
    label: 'Extensions',
    collapsed: true,
    items: _catalog.extensions.map(ext => ({ type: 'autogenerated' as const, dirName: `api/${ext.slug}` })),
  },
];

const sidebars: SidebarsConfig = {
  conceptsSidebar: [
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/intelligence-overview',
        'concepts/agent-policy-overview',
        'concepts/wots-key-management',
        'concepts/omnia-channels',
        'concepts/omnia-vtxo',
        'concepts/relay-modes',
        'concepts/totem-connect',
      ],
    },
  ],

  guidesSidebar: [
    {
      type: 'category',
      label: 'Setup & Configuration',
      collapsed: false,
      items: [
        'guides/typescript-configuration',
      ],
    },
    {
      type: 'category',
      label: 'Example Apps',
      collapsed: false,
      items: [
        'guides/tessa-pay',
        'guides/totem-personal-node',
        'guides/kissvm-studio',
        'guides/statechain-pass',
        'guides/omnia-pocket',
        'guides/channel-factory-wallet',
        'guides/omnia-router-node',
        'guides/totem-community-node',
        'guides/machinepay-edge',
      ],
    },
  ],

  apiSidebar,
};

export default sidebars;
