// RFC-033 — byte-exact parity tests for the Go cgo binding.
//
// The decisive test compares Go output against a vector generated by the
// TypeScript/Rust engine (`testdata-ts-vector.json`): same pkDigest, same full
// public key, same 1088-byte signature, and the TS signature verifies in Go.
package totemcrypto

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

type tsVector struct {
	Seed      string `json:"seed"`
	Index     uint32 `json:"index"`
	Message   string `json:"message"`
	PkDigest  string `json:"pkDigest"`
	PkFull    string `json:"pkFull"`
	Signature string `json:"signature"`
}

func loadVector(t *testing.T) tsVector {
	t.Helper()
	raw, err := os.ReadFile("testdata-ts-vector.json")
	if err != nil {
		t.Fatalf("read vector: %v", err)
	}
	var v tsVector
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse vector: %v", err)
	}
	return v
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("hex %q: %v", s, err)
	}
	return b
}

// Go's pkDigest must equal the TypeScript/Rust digest (byte-exact derivation).
func TestPkDigestMatchesTypeScript(t *testing.T) {
	v := loadVector(t)
	seed := mustHex(t, v.Seed)
	got, err := DerivePKDigest(seed, v.Index)
	if err != nil {
		t.Fatalf("DerivePKDigest: %v", err)
	}
	if hex.EncodeToString(got) != v.PkDigest {
		t.Fatalf("pkDigest mismatch\n got %s\nwant %s", hex.EncodeToString(got), v.PkDigest)
	}
}

// Go's full public key must equal TypeScript's (1088 bytes).
func TestFullPublicKeyMatchesTypeScript(t *testing.T) {
	v :=loadVector(t)
	seed := mustHex(t, v.Seed)
	got, err := DeriveFullPublicKey(seed, v.Index)
	if err != nil {
		t.Fatalf("DeriveFullPublicKey: %v", err)
	}
	if hex.EncodeToString(got) != v.PkFull {
		t.Fatalf("pkFull mismatch (len got=%d want=%d)", len(got), len(v.PkFull)/2)
	}
}

// Go's signature must be byte-identical to TypeScript's (deterministic signing).
func TestSignatureMatchesTypeScript(t *testing.T) {
	v := loadVector(t)
	seed := mustHex(t, v.Seed)
	msg := mustHex(t, v.Message)
	got, err := Sign(seed, v.Index, msg)
	if err != nil {
		t.Fatalf("Sign: %v", err)
	}
	if hex.EncodeToString(got) != v.Signature {
		t.Fatalf("signature mismatch (len got=%d want=%d)", len(got), len(v.Signature)/2)
	}
}

// A TypeScript-produced signature must verify in Go, both by digest and full key.
func TestVerifyTypeScriptSignature(t *testing.T) {
	v := loadVector(t)
	msg := mustHex(t, v.Message)
	sig := mustHex(t, v.Signature)
	pkDigest := mustHex(t, v.PkDigest)
	pkFull := mustHex(t, v.PkFull)

	if !VerifyDigest(sig, msg, pkDigest) {
		t.Fatal("VerifyDigest rejected a TS signature")
	}
	if !Verify(sig, msg, pkFull) {
		t.Fatal("Verify rejected a TS signature")
	}
	// Wrong message must fail (no false accept).
	bad := append([]byte{}, msg...)
	bad[0] ^= 0xff
	if VerifyDigest(sig, bad, pkDigest) {
		t.Fatal("VerifyDigest accepted a tampered message")
	}
}

func TestAddressFromKeypair(t *testing.T) {
	v := loadVector(t)
	seed := mustHex(t, v.Seed)
	addr, err := AddressFromKeypair(seed, v.Index)
	if err != nil {
		t.Fatalf("AddressFromKeypair: %v", err)
	}
	if len(addr) < 6 || addr[:2] != "Mx" {
		t.Fatalf("unexpected address format: %s", addr)
	}
}

func TestTreeKeySignVerify(t *testing.T) {
	seed := make([]byte, 32)
	for i := range seed {
		seed[i] = 0x5a
	}
	tk, err := NewTreeKey(seed, 4, 2)
	if err != nil {
		t.Fatalf("NewTreeKey: %v", err)
	}
	defer tk.Free()

	pk, err := tk.PublicKey()
	if err != nil || len(pk) != 32 {
		t.Fatalf("PublicKey: %v len=%d", err, len(pk))
	}
	msg := make([]byte, 32)
	msg[0] = 1
	sigJSON, err := tk.Sign(msg)
	if err != nil {
		t.Fatalf("Sign: %v", err)
	}
	if !VerifyTreeSignature(pk, msg, sigJSON) {
		t.Fatal("VerifyTreeSignature rejected own signature")
	}
	// Serialization must produce Java-Streamable bytes (non-empty, deterministic).
	ser, err := SerializeTreeSignature(sigJSON)
	if err != nil {
		t.Fatalf("SerializeTreeSignature: %v", err)
	}
	ser2, _ := SerializeTreeSignature(sigJSON)
	if hex.EncodeToString(ser) != hex.EncodeToString(ser2) {
		t.Fatal("serialization is not deterministic")
	}
}
